import 'package:morshed_mock_app/std_model.dart';

List<StdModel> stdModelList = [
  StdModel(
    id: 1,
    onboardingStatus: OnboardingStatus.onboard,
    fullName: "John Doe",
    email: "john.doe@example.com",
    phoneNumber: "123-456-7890",
    lastContacted: DateTime(2023, 10, 15),
    topSubject: "Mathematics",
    worstSubject: "History",
    lastActiveDate: DateTime(2023, 10, 20),
    lastDateCalled: DateTime(2023, 10, 25),
    programName: "Science Major",
    callStatus: CallStatus.success,
  ),
  StdModel(
    id: 2,
    onboardingStatus: OnboardingStatus.followup,
    fullName: "Alice Johnson",
    email: "alice.johnson@example.com",
    phoneNumber: "987-654-3210",
    lastContacted: DateTime(2023, 10, 12),
    topSubject: "English Literature",
    worstSubject: "Physics",
    lastActiveDate: DateTime(2023, 10, 18),
    lastDateCalled: DateTime(2023, 10, 24),
    programName: "Arts Major",
    callStatus: CallStatus.pending,
  ),
  StdModel(
    id: 3,
    onboardingStatus: OnboardingStatus.onboard,
    fullName: "Bob Smith",
    email: "bob.smith@example.com",
    phoneNumber: "555-123-4567",
    lastContacted: DateTime(2023, 10, 10),
    topSubject: "Computer Science",
    worstSubject: "Biology",
    lastActiveDate: DateTime(2023, 10, 16),
    lastDateCalled: DateTime(2023, 10, 22),
    programName: "Computer Science Major",
    callStatus: CallStatus.failed,
  ),
  StdModel(
    id: 4,
    onboardingStatus: OnboardingStatus.followup,
    fullName: "Sarah Williams",
    email: "sarah.williams@example.com",
    phoneNumber: "333-999-7777",
    lastContacted: DateTime(2023, 10, 8),
    topSubject: "Chemistry",
    worstSubject: "Art",
    lastActiveDate: DateTime(2023, 10, 14),
    lastDateCalled: DateTime(2023, 10, 20),
    programName: "Chemistry Major",
    callStatus: CallStatus.success,
  ),
  StdModel(
    id: 5,
    onboardingStatus: OnboardingStatus.onboard,
    fullName: "Emily Brown",
    email: "emily.brown@example.com",
    phoneNumber: "777-444-2222",
    lastContacted: DateTime(2023, 10, 6),
    topSubject: "History",
    worstSubject: "Mathematics",
    lastActiveDate: DateTime(2023, 10, 12),
    lastDateCalled: DateTime(2023, 10, 18),
    programName: "History Major",
    callStatus: CallStatus.pending,
  ),
  StdModel(
    id: 6,
    onboardingStatus: OnboardingStatus.onboard,
    fullName: "David Lee",
    email: "david.lee@example.com",
    phoneNumber: "888-555-3333",
    lastContacted: DateTime(2023, 10, 4),
    topSubject: "Physics",
    worstSubject: "English Literature",
    lastActiveDate: DateTime(2023, 10, 10),
    lastDateCalled: DateTime(2023, 10, 16),
    programName: "Physics Major",
    callStatus: CallStatus.failed,
  ),
  StdModel(
    id: 7,
    onboardingStatus: OnboardingStatus.followup,
    fullName: "Linda Wilson",
    email: "linda.wilson@example.com",
    phoneNumber: "111-222-3333",
    lastContacted: DateTime(2023, 10, 2),
    topSubject: "Biology",
    worstSubject: "Chemistry",
    lastActiveDate: DateTime(2023, 10, 8),
    lastDateCalled: DateTime(2023, 10, 14),
    programName: "Biology Major",
    callStatus: CallStatus.success,
  ),
  StdModel(
    id: 8,
    onboardingStatus: OnboardingStatus.onboard,
    fullName: "James Martin",
    email: "james.martin@example.com",
    phoneNumber: "999-111-8888",
    lastContacted: DateTime(2023, 9, 30),
    topSubject: "Art",
    worstSubject: "Computer Science",
    lastActiveDate: DateTime(2023, 10, 6),
    lastDateCalled: DateTime(2023, 10, 12),
    programName: "Art Major",
    callStatus: CallStatus.pending,
  ),
  StdModel(
    id: 9,
    onboardingStatus: OnboardingStatus.onboard,
    fullName: "Mia Anderson",
    email: "mia.anderson@example.com",
    phoneNumber: "777-222-5555",
    lastContacted: DateTime(2023, 9, 28),
    topSubject: "Mathematics",
    worstSubject: "Physics",
    lastActiveDate: DateTime(2023, 10, 4),
    lastDateCalled: DateTime(2023, 10, 10),
    programName: "Mathematics Major",
    callStatus: CallStatus.failed,
  ),
  StdModel(
    id: 10,
    onboardingStatus: OnboardingStatus.followup,
    fullName: "Michael Taylor",
    email: "michael.taylor@example.com",
    phoneNumber: "555-888-7777",
    lastContacted: DateTime(2023, 9, 26),
    topSubject: "Chemistry",
    worstSubject: "History",
    lastActiveDate: DateTime(2023, 10, 2),
    lastDateCalled: DateTime(2023, 10, 8),
    programName: "Chemistry Major",
    callStatus: CallStatus.success,
  ),
  StdModel(
    id: 11,
    onboardingStatus: OnboardingStatus.followup,
    fullName: "Grace Evans",
    email: "grace.evans@example.com",
    phoneNumber: "222-333-4444",
    lastContacted: DateTime(2023, 9, 18),
    topSubject: "History",
    worstSubject: "Computer Science",
    lastActiveDate: DateTime(2023, 9, 24),
    lastDateCalled: DateTime(2023, 9, 30),
    programName: "History Major",
    callStatus: CallStatus.pending,
  ),
  StdModel(
    id: 12,
    onboardingStatus: OnboardingStatus.onboard,
    fullName: "Ethan White",
    email: "ethan.white@example.com",
    phoneNumber: "666-111-7777",
    lastContacted: DateTime(2023, 9, 16),
    topSubject: "Biology",
    worstSubject: "Mathematics",
    lastActiveDate: DateTime(2023, 9, 22),
    lastDateCalled: DateTime(2023, 9, 28),
    programName: "Biology Major",
    callStatus: CallStatus.success,
  ),
  StdModel(
    id: 13,
    onboardingStatus: OnboardingStatus.onboard,
    fullName: "Ava Parker",
    email: "ava.parker@example.com",
    phoneNumber: "444-555-6666",
    lastContacted: DateTime(2023, 9, 14),
    topSubject: "Computer Science",
    worstSubject: "Physics",
    lastActiveDate: DateTime(2023, 9, 20),
    lastDateCalled: DateTime(2023, 9, 26),
    programName: "Computer Science Major",
    callStatus: CallStatus.failed,
  ),
  StdModel(
    id: 14,
    onboardingStatus: OnboardingStatus.followup,
    fullName: "Logan Hall",
    email: "logan.hall@example.com",
    phoneNumber: "888-222-1111",
    lastContacted: DateTime(2023, 9, 12),
    topSubject: "Art",
    worstSubject: "Chemistry",
    lastActiveDate: DateTime(2023, 9, 18),
    lastDateCalled: DateTime(2023, 9, 24),
    programName: "Art Major",
    callStatus: CallStatus.success,
  ),
  StdModel(
    id: 15,
    onboardingStatus: OnboardingStatus.onboard,
    fullName: "Sophia King",
    email: "sophia.king@example.com",
    phoneNumber: "333-777-8888",
    lastContacted: DateTime(2023, 9, 10),
    topSubject: "Mathematics",
    worstSubject: "History",
    lastActiveDate: DateTime(2023, 9, 16),
    lastDateCalled: DateTime(2023, 9, 22),
    programName: "Mathematics Major",
    callStatus: CallStatus.pending,
  ),
  StdModel(
    id: 16,
    onboardingStatus: OnboardingStatus.onboard,
    fullName: "Noah Turner",
    email: "noah.turner@example.com",
    phoneNumber: "777-888-9999",
    lastContacted: DateTime(2023, 9, 8),
    topSubject: "Physics",
    worstSubject: "English Literature",
    lastActiveDate: DateTime(2023, 9, 14),
    lastDateCalled: DateTime(2023, 9, 20),
    programName: "Physics Major",
    callStatus: CallStatus.failed,
  ),
  StdModel(
    id: 17,
    onboardingStatus: OnboardingStatus.followup,
    fullName: "Liam Hill",
    email: "liam.hill@example.com",
    phoneNumber: "111-222-3333",
    lastContacted: DateTime(2023, 9, 6),
    topSubject: "Biology",
    worstSubject: "Chemistry",
    lastActiveDate: DateTime(2023, 9, 12),
    lastDateCalled: DateTime(2023, 9, 18),
    programName: "Biology Major",
    callStatus: CallStatus.success,
  ),
  StdModel(
    id: 18,
    onboardingStatus: OnboardingStatus.onboard,
    fullName: "Mila Morris",
    email: "mila.morris@example.com",
    phoneNumber: "999-555-1111",
    lastContacted: DateTime(2023, 9, 4),
    topSubject: "Art",
    worstSubject: "Computer Science",
    lastActiveDate: DateTime(2023, 9, 10),
    lastDateCalled: DateTime(2023, 9, 16),
    programName: "Art Major",
    callStatus: CallStatus.pending,
  ),
  StdModel(
    id: 19,
    onboardingStatus: OnboardingStatus.onboard,
    fullName: "Jack Scott",
    email: "jack.scott@example.com",
    phoneNumber: "777-555-3333",
    lastContacted: DateTime(2023, 9, 2),
    topSubject: "Mathematics",
    worstSubject: "Physics",
    lastActiveDate: DateTime(2023, 9, 8),
    lastDateCalled: DateTime(2023, 9, 14),
    programName: "Mathematics Major",
    callStatus: CallStatus.failed,
  ),
  StdModel(
    id: 20,
    onboardingStatus: OnboardingStatus.followup,
    fullName: "Emma Baker",
    email: "emma.baker@example.com",
    phoneNumber: "555-999-7777",
    lastContacted: DateTime(2023, 8, 31),
    topSubject: "Chemistry",
    worstSubject: "History",
    lastActiveDate: DateTime(2023, 9, 6),
    lastDateCalled: DateTime(2023, 9, 12),
    programName: "Chemistry Major",
    callStatus: CallStatus.success,
  ),
  StdModel(
    id: 21,
    onboardingStatus: OnboardingStatus.onboard,
    fullName: "Oliver Young",
    email: "oliver.young@example.com",
    phoneNumber: "222-333-4444",
    lastContacted: DateTime(2023, 8, 29),
    topSubject: "English Literature",
    worstSubject: "Physics",
    lastActiveDate: DateTime(2023, 9, 4),
    lastDateCalled: DateTime(2023, 9, 10),
    programName: "English Major",
    callStatus: CallStatus.pending,
  ),
  StdModel(
    id: 22,
    onboardingStatus: OnboardingStatus.followup,
    fullName: "Charlotte Green",
    email: "charlotte.green@example.com",
    phoneNumber: "666-777-8888",
    lastContacted: DateTime(2023, 8, 27),
    topSubject: "History",
    worstSubject: "Biology",
    lastActiveDate: DateTime(2023, 9, 2),
    lastDateCalled: DateTime(2023, 9, 8),
    programName: "History Major",
    callStatus: CallStatus.failed,
  ),
  StdModel(
    id: 23,
    onboardingStatus: OnboardingStatus.onboard,
    fullName: "William Hall",
    email: "william.hall@example.com",
    phoneNumber: "555-666-7777",
    lastContacted: DateTime(2023, 8, 25),
    topSubject: "Computer Science",
    worstSubject: "Mathematics",
    lastActiveDate: DateTime(2023, 8, 31),
    lastDateCalled: DateTime(2023, 9, 6),
    programName: "Computer Science Major",
    callStatus: CallStatus.success,
  ),
  StdModel(
    id: 24,
    onboardingStatus: OnboardingStatus.followup,
    fullName: "Scarlett Taylor",
    email: "scarlett.taylor@example.com",
    phoneNumber: "888-111-6666",
    lastContacted: DateTime(2023, 8, 23),
    topSubject: "Art",
    worstSubject: "Chemistry",
    lastActiveDate: DateTime(2023, 8, 29),
    lastDateCalled: DateTime(2023, 9, 4),
    programName: "Art Major",
    callStatus: CallStatus.failed,
  ),
  StdModel(
    id: 25,
    onboardingStatus: OnboardingStatus.onboard,
    fullName: "Henry Martin",
    email: "henry.martin@example.com",
    phoneNumber: "444-777-9999",
    lastContacted: DateTime(2023, 8, 21),
    topSubject: "Mathematics",
    worstSubject: "Physics",
    lastActiveDate: DateTime(2023, 8, 27),
    lastDateCalled: DateTime(2023, 9, 2),
    programName: "Mathematics Major",
    callStatus: CallStatus.pending,
  ),
  StdModel(
    id: 26,
    onboardingStatus: OnboardingStatus.onboard,
    fullName: "Nora Lewis",
    email: "nora.lewis@example.com",
    phoneNumber: "333-444-5555",
    lastContacted: DateTime(2023, 8, 19),
    topSubject: "Physics",
    worstSubject: "English Literature",
    lastActiveDate: DateTime(2023, 8, 25),
    lastDateCalled: DateTime(2023, 8, 31),
    programName: "Physics Major",
    callStatus: CallStatus.success,
  ),
  StdModel(
    id: 27,
    onboardingStatus: OnboardingStatus.followup,
    fullName: "Liam Wilson",
    email: "liam.wilson@example.com",
    phoneNumber: "222-333-4444",
    lastContacted: DateTime(2023, 8, 17),
    topSubject: "Biology",
    worstSubject: "Chemistry",
    lastActiveDate: DateTime(2023, 8, 23),
    lastDateCalled: DateTime(2023, 8, 29),
    programName: "Biology Major",
    callStatus: CallStatus.pending,
  ),
  StdModel(
    id: 28,
    onboardingStatus: OnboardingStatus.onboard,
    fullName: "Ella Turner",
    email: "ella.turner@example.com",
    phoneNumber: "555-666-7777",
    lastContacted: DateTime(2023, 8, 15),
    topSubject: "Art",
    worstSubject: "Computer Science",
    lastActiveDate: DateTime(2023, 8, 21),
    lastDateCalled: DateTime(2023, 8, 27),
    programName: "Art Major",
    callStatus: CallStatus.failed,
  ),
  StdModel(
    id: 29,
    onboardingStatus: OnboardingStatus.onboard,
    fullName: "Sebastian Hill",
    email: "sebastian.hill@example.com",
    phoneNumber: "888-444-1111",
    lastContacted: DateTime(2023, 8, 13),
    topSubject: "Mathematics",
    worstSubject: "Physics",
    lastActiveDate: DateTime(2023, 8, 19),
    lastDateCalled: DateTime(2023, 8, 25),
    programName: "Mathematics Major",
    callStatus: CallStatus.success,
  ),
  StdModel(
    id: 30,
    onboardingStatus: OnboardingStatus.followup,
    fullName: "Avery King",
    email: "avery.king@example.com",
    phoneNumber: "333-777-8888",
    lastContacted: DateTime(2023, 8, 11),
    topSubject: "Chemistry",
    worstSubject: "History",
    lastActiveDate: DateTime(2023, 8, 17),
    lastDateCalled: DateTime(2023, 8, 23),
    programName: "Chemistry Major",
    callStatus: CallStatus.failed,
  ),
  StdModel(
    id: 31,
    onboardingStatus: OnboardingStatus.onboard,
    fullName: "Liam Davis",
    email: "liam.davis@example.com",
    phoneNumber: "222-555-7777",
    lastContacted: DateTime(2023, 8, 9),
    topSubject: "History",
    worstSubject: "Computer Science",
    lastActiveDate: DateTime(2023, 8, 15),
    lastDateCalled: DateTime(2023, 8, 21),
    programName: "History Major",
    callStatus: CallStatus.success,
  ),
  StdModel(
    id: 32,
    onboardingStatus: OnboardingStatus.followup,
    fullName: "Olivia Rodriguez",
    email: "olivia.rodriguez@example.com",
    phoneNumber: "666-333-1111",
    lastContacted: DateTime(2023, 8, 7),
    topSubject: "Biology",
    worstSubject: "Mathematics",
    lastActiveDate: DateTime(2023, 8, 13),
    lastDateCalled: DateTime(2023, 8, 19),
    programName: "Biology Major",
    callStatus: CallStatus.failed,
  ),
  StdModel(
    id: 33,
    onboardingStatus: OnboardingStatus.onboard,
    fullName: "James Hall",
    email: "james.hall@example.com",
    phoneNumber: "555-777-9999",
    lastContacted: DateTime(2023, 8, 5),
    topSubject: "Computer Science",
    worstSubject: "Physics",
    lastActiveDate: DateTime(2023, 8, 11),
    lastDateCalled: DateTime(2023, 8, 17),
    programName: "Computer Science Major",
    callStatus: CallStatus.pending,
  ),
  StdModel(
    id: 34,
    onboardingStatus: OnboardingStatus.followup,
    fullName: "Charlotte Garcia",
    email: "charlotte.garcia@example.com",
    phoneNumber: "888-444-1111",
    lastContacted: DateTime(2023, 8, 3),
    topSubject: "Art",
    worstSubject: "Chemistry",
    lastActiveDate: DateTime(2023, 8, 9),
    lastDateCalled: DateTime(2023, 8, 15),
    programName: "Art Major",
    callStatus: CallStatus.success,
  ),
  StdModel(
    id: 35,
    onboardingStatus: OnboardingStatus.onboard,
    fullName: "Ethan Lopez",
    email: "ethan.lopez@example.com",
    phoneNumber: "444-777-2222",
    lastContacted: DateTime(2023, 8, 1),
    topSubject: "Mathematics",
    worstSubject: "Physics",
    lastActiveDate: DateTime(2023, 8, 7),
    lastDateCalled: DateTime(2023, 8, 13),
    programName: "Mathematics Major",
    callStatus: CallStatus.failed,
  ),
  StdModel(
    id: 36,
    onboardingStatus: OnboardingStatus.onboard,
    fullName: "Isabella Johnson",
    email: "isabella.johnson@example.com",
    phoneNumber: "333-222-5555",
    lastContacted: DateTime(2023, 7, 30),
    topSubject: "Physics",
    worstSubject: "English Literature",
    lastActiveDate: DateTime(2023, 8, 5),
    lastDateCalled: DateTime(2023, 8, 11),
    programName: "Physics Major",
    callStatus: CallStatus.success,
  ),
  StdModel(
    id: 37,
    onboardingStatus: OnboardingStatus.followup,
    fullName: "Michael Smith",
    email: "michael.smith@example.com",
    phoneNumber: "222-555-7777",
    lastContacted: DateTime(2023, 7, 28),
    topSubject: "Biology",
    worstSubject: "Chemistry",
    lastActiveDate: DateTime(2023, 8, 3),
    lastDateCalled: DateTime(2023, 8, 9),
    programName: "Biology Major",
    callStatus: CallStatus.pending,
  ),
  StdModel(
    id: 38,
    onboardingStatus: OnboardingStatus.onboard,
    fullName: "Ava Turner",
    email: "ava.turner@example.com",
    phoneNumber: "555-777-9999",
    lastContacted: DateTime(2023, 7, 26),
    topSubject: "Art",
    worstSubject: "Computer Science",
    lastActiveDate: DateTime(2023, 8, 1),
    lastDateCalled: DateTime(2023, 8, 7),
    programName: "Art Major",
    callStatus: CallStatus.failed,
  ),
  StdModel(
    id: 39,
    onboardingStatus: OnboardingStatus.onboard,
    fullName: "Noah Martinez",
    email: "noah.martinez@example.com",
    phoneNumber: "888-444-1111",
    lastContacted: DateTime(2023, 7, 24),
    topSubject: "Mathematics",
    worstSubject: "Physics",
    lastActiveDate: DateTime(2023, 7, 30),
    lastDateCalled: DateTime(2023, 8, 5),
    programName: "Mathematics Major",
    callStatus: CallStatus.success,
  ),
  StdModel(
    id: 40,
    onboardingStatus: OnboardingStatus.followup,
    fullName: "Mia Robinson",
    email: "mia.robinson@example.com",
    phoneNumber: "333-777-8888",
    lastContacted: DateTime(2023, 7, 22),
    topSubject: "Chemistry",
    worstSubject: "History",
    lastActiveDate: DateTime(2023, 7, 28),
    lastDateCalled: DateTime(2023, 8, 3),
    programName: "Chemistry Major",
    callStatus: CallStatus.failed,
  ),
];
